### ISSUE TITLE
`cases` for coinductive datatypes does not seem to work as expected

### ISSUE THREAD

**Issue by ghost** [leanprover/lean3#1778]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

`cases` for coinductive datatypes does not seem to work as expected.
(Having said that, since I'm fairly new to Lean, I can't be sure if this is really an "unexpected" behavior. I will appreciate your comments.)

### Steps to Reproduce

Suppose you have the following code snippet:
```
inductive term : Type
| pair : term → term → term

coinductive infer : term → Prop
| and : ∀ Γ Δ, infer Γ → infer Δ → infer (term.pair Γ Δ)

theorem pr : ∀ Γ Δ, infer (term.pair Γ Δ) → infer Γ :=
begin
  intros,
  cases a,
  admit
end
```

Then you get an error at "cases a" (`"cases tactic failed, it is not applicable to the given hypothesis"`).
On the other hand, if you replace the word "coinductive" with "inductive", you of course get no errors.
I suppose the "cases a" in the case of coinduction is expected to work just as in the case of induction.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

Lean (version 3.2.0, Release) on macOS Sierra 10.12.6

**Comment by digama0** [comment]
It's not a great answer, but `coinductive` is not implemented in the kernel, it is a user extension, so it does not play well with many tactics, unlike `inductive` which is primitive. This is on the roadmap, but it is likely to be a problem for a while.

**Comment by johoelzl** [comment]
`coinductive` produces a `cases_on` rule. It should be working with `induction a using infer.cases_on`. There is also a `coinduction` tactic.

**Comment by ghost** [comment]
Thank you for your kind comments.
Regarding to the `cases_on` rule and the `coinduction` tactic, I still have a problem.
If I try to prove the theorem using `cases_on`, in other words, if I write as follows:
```
theorem pr : ∀ Γ Δ, infer (term.pair Γ Δ) → infer Γ :=
begin
  intros,
  induction a using infer.cases_on,
  admit
end
```
then the output of the goal buffer after the `cases_on` line is
```
Γ Δ : term,
a : infer (term.pair Γ Δ)
⊢ infer a

Γ Δ Γ_1 Δ_1 : term,
a_1 : infer Γ_1,
a_2 : infer Δ_1
⊢ infer Γ
```
which is obviously false. On the other hand, if I try the `coinduction` tactic:
```
theorem pr : ∀ Γ Δ, infer (term.pair Γ Δ) → infer Γ :=
begin
  intros,
  coinduction infer.corec_on,
  admit
end
```
then the output of the goal buffer after the `coinduction` line is
```
Γ Δ : term,
a : infer (term.pair Γ Δ)
⊢ ∃ (Γ_1 Δ : term), Γ = Γ_1 ∧ Γ = Δ ∧ term.pair Γ_1 Δ = Γ
```
which is again obviously false.
Are these behaviors are as expected?
If so, would you mind if I ask you to show me how I'm doing wrong?
I would like to prove "if a and b, then a" in this coinductive situation.

(I have read `lean/tests/lean/run/coinductive.lean`, but I could not figure out how can I prove statements coinductively)

**Comment by fpvandoorn** [comment]
Here is one way to prove it. 
```lean
theorem pr : ∀ Γ Δ, infer (term.pair Γ Δ) → infer Γ :=
begin
  intros Γ Δ,
  have : Π{a}, infer a → a = term.pair Γ Δ → infer Γ,
  { intros a H, refine infer.cases_on H _,
    intros Γ' Δ' H2 H3 Heq, injection Heq with Heq2 Heq3, subst Heq2, exact H2 },
  intro H, exact this H rfl
end
```
To apply `infer.cases_on` (and get something useful) you need to apply it to an assumption `infer a` where `a` is a variable. To not forget the form of `a`, we add an equality `a = term.pair Γ Δ` to the goal.
For inductive types, the `cases` tactic would do most of this for you, but that's not implemented for coinductive types yet, so for now, you can use this approach.

**Comment by ghost** [comment]
With a little modification related to the interaction between term-style and tactic-style, the proof you gave worked completely in my environment.
Thanks to your helpful comments, now I'm getting used to coinductive proofs in Lean.
Sorry for my newbie question. I'm really thank you.
