### ISSUE TITLE
lean-mode options

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean3#489]
I have some problems with the options for lean-mode (the ones accessible from `menu-bar > Lean > Customize lean-mode`).

My current options are

```
Hide Lean Flycheck Checker Options: 
("--keep-going" "999" "--flycheck" "--flycheck-max-messages" "100" "-M" "100" "-T")

Hide Lean Server Options: ("-M" "100" "-T")
```

However, for a while I get the following error when opening a `.lean` or `.hlean` file, because of the option `-T`:

```
Checker lean-checker returned non-zero exit code 2, but no errors from output: usage: linja [-h] [--flycheck]
             [--flycheck-max-messages [FLYCHECK_MAX_MESSAGES]] [--cache CACHE]
             [--directory DIRECTORY] [--lean-config-option LEAN_CONFIG_OPTION]
             [--verbose] [--memory [MEMORY]] [--keep-going [KEEP_GOING]]
             [--discard] [--to_axiom] [--trust]
             [targets [targets ...]]
linja: error: unrecognized arguments: -T

Checker definition probably flawed.
```

Secondly, my memory has filled up a couple of times last week because of lean-mode or flycheck (or at least: my computer became unresponsive), so I'm wondering whether the option `-M` is still working correctly.

**Comment by leodemoura** [comment]
> I'm wondering whether the option -M is still working correctly.

The option `-M` should work. Do you recall what you were doing?
I can try to reproduce it.

Thanks

**Comment by fpvandoorn** [comment]
I consistently get a crash when I open and compile the following file (the file for me is placed in `hott/hit`, but I think that shouldn't matter):

https://gist.github.com/fpvandoorn/4f18937768fdfc498d0f

You probably need to be in branch `fpvandoorn/master` for this to work (note: the file is supposed to raise quite some errors).

I also tried to use the commands `ulimit -v` and `ulimit -m`, but I still get a crash. Is it possible that something other than my memory fills up and makes my computer unresponsive? Unfortunately it becomes so unresponsive I cannot even use something like `alt-F2 killall lean`. I power down my computer using the power button :-(

**Comment by leodemoura** [comment]
I will investigate.

> I also tried to use the commands ulimit -v and ulimit -m, but I still get a crash. 

This is strange. `ulimit` is enforced by the OS.

**Comment by fpvandoorn** [comment]
I tried the options in different sessions. Now I use them both at the same time, my system doesn't crash anymore, but I get the error

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

This happens when compiling `definition my_tr_eq1` (or at least: that definition throws the last error).

**Comment by leodemoura** [comment]
> Now I use them both at the same time, my system doesn't crash anymore, but I get the error

We should trap the exception `std::bad_alloc`, and produce a nicer error message.
However, it will be just a "cosmetic thing". The Lean process will be interrupted.

**Comment by fpvandoorn** [comment]
That would be nice... But the more important thing is to make sure I don't have to rely on `ulimit` to make sure lean-mode doesn't use all memory.

**Comment by leodemoura** [comment]
> That would be nice... But the more important thing is to make sure I don't have to rely on ulimit to make sure lean-mode doesn't use all memory.

I agree.

**Comment by leodemoura** [comment]
@fpvandoorn I tried to reproduce the problem at

```
https://gist.github.com/fpvandoorn/4f18937768fdfc498d0f
```

but the declaration `eq_partial` is missing.
I tried your branch, but it did not work.

**Comment by fpvandoorn** [comment]
That is "intended" (I was in the middle of renaming a bunch of stuff).

>  (note: the file is supposed to raise quite some errors).

I updated [the gist](https://gist.github.com/fpvandoorn/4f18937768fdfc498d0f) to use the new `intros [ ... ]` notation. If I then compile it in `blessed/master` of this morning (6f6d106) (probably also after newer commits), I get the following output (if I use both `ulimit -m` and `ulimit -v`)

```
-*- mode: compilation; default-directory: "~/projects/lean/hott/" -*-
Compilation started at Mon Apr 20 19:36:53

~/projects/lean/bin/lean -Dpp.width=120  /home/floris/projects/lean/hott/test.hlean

(... bunch of errors ...)

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Compilation aborted (core dumped) at Mon Apr 20 19:37:02
```

**Comment by leodemoura** [comment]
I fixed the bug that was consuming all the memory, add extra memory checks, and trapped `std::bad_alloc` (now Lean produces an `out of memory` message instead of 

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

@fpvandoorn your example now terminates immediately.
I'm closing this issue.
If you find other problems, we can reopen it.

**Comment by fpvandoorn** [comment]
Great!

By the way, I do still have the other issue I posted here, about the error message when I add the `"-T"` flag to the Emacs `Lean Flycheck Checker Options` or `Lean Server Options`. Does that flag work for you?

**Comment by leodemoura** [comment]
Do we have an option `-T`? 
If we had it, we don't have it anymore in the latest version.
What did it suppose to do?

**Comment by fpvandoorn** [comment]
You mentioned it [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/lean-discuss/yVaeTuwjHGs/qhCBRIVYzigJ)

> [...] using option -T (assume imported modules are type correct).

and showed a screenshot with it [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/lean-discuss/yVaeTuwjHGs/ISJ_Oe2Q0hkJ)

**Comment by leodemoura** [comment]
I see. This is not needed anymore.
This is the default behavior now. 
To retype-check imported modules, we must use `-t 0` (trust level 0).
I think not type checking imported modules is a very reasonable default behavior.
Lean already computes the file checksum and checks whether it matches the value stored in the file. 
So, by using `-t 0`, we are essentially protecting ourselves from malicious users that went inside of the .olean file and modified the bytes (and the checksum) to make it look like a valid one.

**Comment by fpvandoorn** [comment]
Ok. I did not know that became the default behavior (probably you mailed it at some point, but I forgot). Then this issue is indeed completely resolved.
